# noinspection YAMLSchemaValidation
version: 1

labels:
  # Type labels
  - label: "@type/build"
    title: '^build(?:\(.+\))?\!?:'

  - label: "@type/ci"
    title: '^ci(?:\(.+\))?\!?:'
    files:
      - '\.github/.+'
      - "scripts/.+"
      - "tools/.+"

  - label: "@type/docs"
    title: '^docs:(?:\(.+\))?\!?:'
    files:
      - "docs/.+"
      - "**/README.md$"

  - label: "@type/feature"
    title: '^feat:(?:\(.+\))?\!?:'

  - label: "@type/fix"
    title: '^fix:(?:\(.+\))?\!?:'

  - label: "@type/improve"
    title: '^(style|refactor|perf)(?:\(.+\))?\!?:'

  # Package labels
  - label: "@articles"
    files:
      - "articles/.+"

  - label: "@books"
    files:
      - "books/.+"
